apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "episilia-tail.name" . }}
  labels:
    {{- include "episilia-tail.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.global.tail.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "episilia-tail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "episilia-tail.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "episilia-tail.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.tail.image.repository }}:{{ .Values.global.tail.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9005
              protocol: TCP
          envFrom:
          - configMapRef:
              name: episilia-config
          env:
            - name: ops.server.mode
              value: tail
            - name: gateway.api.http.port
              value: "9005"
            - name: kafka.metadata.broker.list
              valueFrom:
                configMapKeyRef:
                  key: kafka.internal.broker.list
                  name: episilia-config
          resources:
            {{- toYaml .Values.global.tail.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

