apiVersion: v1
kind: Service
metadata:
  name: {{ include "episilia-tail.name" . }}
  labels:
    {{- include "episilia-tail.labels" . | nindent 4 }}
{{- with .Values.global.search.annotations }}
  annotations:
{{ toYaml . | indent 4  }}
{{- end }}
spec:
  type: {{ .Values.global.search.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9005
      protocol: TCP
      name: http
  selector:
    {{- include "episilia-tail.selectorLabels" . | nindent 4 }}
