apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "episilia-search-ondemand.name" . }}
  labels:
    {{- include "episilia-search-ondemand.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.global.ondemandsearch.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "episilia-search-ondemand.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "episilia-search-ondemand.labels" . | nindent 8 }}
        # {{- with .Values.podLabels }}
        # {{- toYaml . | nindent 8 }}
        # {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "episilia-search-ondemand.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: {{ template "episilia-search-ondemand.name" . }}
      {{- if .Values.global.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "episilia-search-ondemand.name" . }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.livesearch.image.repository }}:{{ .Values.global.livesearch.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
          envFrom:
          - configMapRef:
              name: episilia-config
          env:
            - name: ops.server.mode
              value: search
            - name: search.mode
              value: "ondemand"
            - name: kafka.group.search
              valueFrom:
                fieldRef: {fieldPath: metadata.name}
            - name: kafka.topic.index.live
              value: "{{.Values.global.ondemandsearch.topic.index.live}}"
            - name: kafka.topic.index.optimized
              value: "{{.Values.global.ondemandsearch.topic.index.optimized}}"
            - name: ops.work.dir
              value: "/data/search-ondemand"
            - name: RES_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  divisor: 1m
                  resource: requests.cpu
            - name: RES_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: 1m
                  resource: limits.cpu
            - name: RES_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  divisor: 1Mi
                  resource: requests.memory
            - name: RES_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: 1Mi
                  resource: limits.memory

          volumeMounts:
          - name: {{ template "episilia-search-ondemand.name" . }}
            mountPath: "/data"
          resources:
            {{- toYaml .Values.global.ondemandsearch.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}          
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
