apiVersion: v1
kind: Service
metadata:
  name: {{ include "episilia-search-ondemand.name" . }}
  labels:
    {{- include "episilia-search-ondemand.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4040
      protocol: TCP
      name: http
  selector:
    {{- include "episilia-search-ondemand.selectorLabels" . | nindent 4 }}
