apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redpanda.name" . }}
  labels:
    {{- include "redpanda.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    redpanda:
        data_directory: /var/lib/redpanda/data
        rpc_server:
            address: 0.0.0.0
            port: 33145
        advertised_rpc_api:
            address: 0.0.0.0
            port: 33145
        kafka_api:
            - address: 0.0.0.0
              port: {{ .Values.global.redpanda.ports.kafka }}         #configurable
              name: kafka
        kafka_api_tls:
            - name: "kafka"
              enabled: false
        admin:
            - address: 0.0.0.0
              port: {{ .Values.global.redpanda.ports.admin }}         #configurable
              name: admin
        node_id: 0
        seed_servers:
            - host:
                address: redpanda-0.redpanda.default.svc.cluster.local.
                port: 33145
        developer_mode: false
        log_segment_size: 536870912
        auto_create_topics_enabled: true
        delete_retention_ms: {{.Values.global.redpanda.retention}}
        enable_idempotence: false
        enable_transactions: false
    rpk:
        enable_usage_stats: true
        tune_network: false
        tune_disk_scheduler: false
        tune_disk_nomerges: false
        tune_disk_write_cache: false
        tune_disk_irq: false
        tune_fstrim: false
        tune_cpu: false
        tune_aio_events: false
        tune_clocksource: false
        tune_swappiness: false
        tune_transparent_hugepages: false
        enable_memory_locking: false
        tune_coredump: false
        coredump_dir: /var/lib/redpanda/coredump
        tune_ballast_file: false
        overprovisioned: false
    pandaproxy:
        pandaproxy_api:
            - address: 0.0.0.0
              port: {{ .Values.global.redpanda.ports.proxy }}         #configurable
              name: proxy
    schema_registry:
        schema_registry_api:
            - address: 0.0.0.0
              port: 8081         #configurable
              name: schema-registry

