apiVersion: v1
kind: Service
metadata:
  name: {{ include "redpanda.name" . }}
  labels:
    {{- include "redpanda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: admin
      protocol: TCP
      port: {{ .Values.global.redpanda.ports.admin }}
      targetPort: {{ .Values.global.redpanda.ports.admin }}
    - name: kafka
      protocol: TCP
      port: {{ .Values.global.redpanda.ports.kafka }}
      targetPort: {{ .Values.global.redpanda.ports.kafka }}
    - name: proxy
      protocol: TCP
      port: {{ .Values.global.redpanda.ports.proxy }}
      targetPort: {{ .Values.global.redpanda.ports.proxy }}

  selector:
    {{- include "redpanda.selectorLabels" . | nindent 4 }}
