apiVersion: v1
kind: ConfigMap
metadata:
  name: episilia-config
data:
  client.env: {{ .Values.global.client.env | quote }}
  client.id: {{ .Values.global.client.id | quote }}
  client.license.key: {{ .Values.global.client.license.key | quote }}
  datastore.s3logs: s3logs
  datastore.stores.cache.enabled: "false"
  {{- if .Values.minio.enabled }}
  datastore.stores.stage.s3.accesskey: {{ .Values.global.datastore.s3logs.s3.accesskey | quote }}
  datastore.stores.stage.s3.secretkey: {{ .Values.global.datastore.s3logs.s3.secretkey | quote }}
  datastore.stores.stage.s3.endpoint.url: {{ .Values.global.datastore.s3logs.s3.endpoint.url | quote }}
  datastore.stores.stage.s3.region: {{ .Values.global.datastore.s3logs.s3.region | quote }}
  datastore.stores.stage.s3.bucket: {{ .Values.global.datastore.s3logs.s3.bucket | quote }}
  datastore.stores.stage.s3.folder: {{ .Values.global.datastore.s3logs.s3.folder | quote }}
  datastore.stores.stage.s3.sign.payload: {{ .Values.global.datastore.s3logs.s3.sign.payload | quote }}
  datastore.stores.stage.s3.work.folder: {{ .Values.global.datastore.s3logs.s3.work.folder | quote }}
  datastore.stores.stage.s3.useArn: {{ .Values.global.datastore.s3logs.s3.useArn | quote }}
  datastore.stores.stage.s3.assumeRole: {{ .Values.global.datastore.s3logs.s3.assumeRole | quote }}
  datastore.stores.stage.s3.https: {{ .Values.global.datastore.s3logs.s3.https | quote }}
  datastore.stores.stage.s3.pathstyle.access: {{ .Values.global.datastore.s3logs.s3.pathstyle.access | quote }}
  datastore.stores.stage.s3.url.prefix: {{ .Values.global.datastore.s3logs.s3.url.prefix | quote }}
  {{- else }}
  datastore.stores.stage.s3.accesskey: {{ .Values.global.datastore.s3.accesskey | quote }}
  datastore.stores.stage.s3.secretkey: {{ .Values.global.datastore.s3.secretkey | quote }}
  datastore.stores.stage.s3.endpoint.url: {{ .Values.global.datastore.s3.endpoint.url | quote }}
  datastore.stores.stage.s3.region: {{ .Values.global.datastore.s3.region | quote }}
  datastore.stores.stage.s3.bucket: {{ .Values.global.datastore.s3.bucket | quote }}
  datastore.stores.stage.s3.folder: {{ .Values.global.datastore.s3.folder | quote }}
  datastore.stores.stage.s3.sign.payload: {{ .Values.global.datastore.s3.sign.payload | quote }}
  datastore.stores.stage.s3.work.folder: {{ .Values.global.datastore.s3.work.folder | quote }}
  datastore.stores.stage.s3.useArn: {{ .Values.global.datastore.s3.useArn | quote }}
  datastore.stores.stage.s3.assumeRole: {{ .Values.global.datastore.s3.assumeRole | quote }}
  datastore.stores.stage.s3.https: {{ .Values.global.datastore.s3.https | quote }}
  datastore.stores.stage.s3.pathstyle.access: {{ .Values.global.datastore.s3logs.s3.pathstyle.access | quote }}
  datastore.stores.stage.s3.url.prefix: {{ .Values.global.datastore.s3.url.prefix | quote }}
  {{- end }}  
  datastore.stores.final.s3.accesskey: {{ .Values.global.datastore.s3.accesskey | quote }}
  datastore.stores.final.s3.secretkey: {{ .Values.global.datastore.s3.secretkey | quote }}
  datastore.stores.final.s3.endpoint.url: {{ .Values.global.datastore.s3.endpoint.url | quote }}
  datastore.stores.final.s3.region: {{ .Values.global.datastore.s3.region | quote }}
  datastore.stores.final.s3.bucket: {{ .Values.global.datastore.s3.bucket | quote }}
  datastore.stores.final.s3.folder: {{ .Values.global.datastore.s3.folder | quote }}
  datastore.stores.final.s3.sign.payload: {{ .Values.global.datastore.s3.sign.payload | quote }}
  datastore.stores.final.s3.work.folder: {{ .Values.global.datastore.s3.work.folder | quote }}
  datastore.stores.final.s3.useArn: {{ .Values.global.datastore.s3.useArn | quote }}
  datastore.stores.final.s3.assumeRole: {{ .Values.global.datastore.s3.assumeRole | quote }}
  datastore.stores.s3logs.enabled: {{ .Values.global.datastore.s3logs.enabled| quote }}
  datastore.stores.s3logs.s3.accesskey: {{ .Values.global.datastore.s3logs.s3.accesskey | quote }}
  datastore.stores.s3logs.s3.secretkey: {{ .Values.global.datastore.s3logs.s3.secretkey | quote }}
  datastore.stores.s3logs.s3.endpoint.url: {{ .Values.global.datastore.s3logs.s3.endpoint.url | quote }}
  datastore.stores.s3logs.s3.region: {{ .Values.global.datastore.s3logs.s3.region | quote }}
  datastore.stores.s3logs.s3.bucket: {{ .Values.global.datastore.s3logs.s3.bucket | quote }}
  datastore.stores.s3logs.s3.folder: {{ .Values.global.datastore.s3logs.s3.folder | quote }}
  datastore.stores.s3logs.s3.sign.payload: {{ .Values.global.datastore.s3logs.s3.sign.payload | quote }}
  datastore.stores.s3logs.s3.work.folder: {{ .Values.global.datastore.s3logs.s3.work.folder | quote }}
  datastore.stores.s3logs.s3.useArn: {{ .Values.global.datastore.s3logs.s3.useArn | quote }}
  datastore.stores.s3logs.s3.assumeRole: {{ .Values.global.datastore.s3logs.s3.assumeRole | quote }}
  datastore.stores.s3logs.s3.sourcefolder: {{ .Values.global.datastore.s3logs.s3.sourcefolder | quote }}
  datastore.stores.s3logs.s3.https: {{ .Values.global.datastore.s3logs.s3.https | quote }}
  datastore.stores.s3logs.s3.pathstyle.access: {{ .Values.global.datastore.s3logs.s3.pathstyle.access | quote }}
  datastore.stores.s3logs.s3.url.prefix: {{ .Values.global.datastore.s3logs.s3.url.prefix | quote }}
  indexer.ops.pause.consume.file.max.count: {{ .Values.global.indexer.ops.pause.consume.file.max.count | quote }}
  indexer.ops.pause.consume.record.max.count: {{ .Values.global.indexer.ops.pause.consume.record.max.count | quote }}
  indexer.ops.pause.consume.record.size.max.mb: {{ .Values.global.indexer.ops.pause.consume.record.size.max.mb | quote }}  
  indexer.schema.appid.fixed: {{ .Values.global.indexer.schema.appid.fixed | quote }}
  indexer.schema.appid.keys: {{ .Values.global.indexer.schema.appid.keys | quote }}
  indexer.schema.tenantid.fixed: {{ .Values.global.indexer.schema.tenantid.fixed | quote }}
  indexer.schema.tenantid.keys: {{ .Values.global.indexer.schema.tenantid.keys | quote }}
  indexer.schema.exclude: {{ .Values.global.indexer.schema.exclude | quote }}
  indexer.schema.message.key: {{ .Values.global.indexer.schema.message.key | quote }}
  indexer.schema.timestamp.formats: {{ .Values.global.indexer.schema.timestamp.formats | quote }}
  indexer.schema.timestamp.key: {{ .Values.global.indexer.schema.timestamp.key | quote }}
  indexer.tail.enable: {{.Values.global.indexer.tail.enable | quote }}
  indexer.alert.enable: {{.Values.global.indexer.alert.enable | quote }}
  indexer.tail.maxwait.ms: {{.Values.global.indexer.tail.maxwait.ms | quote }}
  indexer.logs.source: {{.Values.global.indexer.logs.source | quote }}
  indexer.alert.rules.file.url: {{.Values.global.indexer.alert.rules.file.url | quote }}
  indexer.alert.prometheus.gateway: {{.Values.global.indexer.alert.prometheus.gateway | quote }}
  kafka.group.spike: {{ .Values.global.kafka.group.spike | quote }}
  kafka.group.search: {{ .Values.global.kafka.group.search | quote }}
  kafka.indexer.group: {{ .Values.global.kafka.indexer.group | quote }}
  kafka.indexer.logs.topics: {{ .Values.global.kafka.indexer.logs.topics | quote }}
  kafka.indexer.broker.list: {{ .Values.global.kafka.indexer.broker.list | quote }}
  kafka.indexer.broker.security.mode: {{ .Values.global.kafka.indexer.broker.security.mode | quote }}
  kafka.indexer.broker.security.protocol: {{ .Values.global.kafka.indexer.broker.security.protocol | quote }}
  kafka.indexer.broker.sasl.mechanism: {{ .Values.global.kafka.indexer.broker.sasl.mechanism | quote }}
  kafka.indexer.broker.sasl.username: {{ .Values.global.kafka.indexer.broker.sasl.username | quote }}
  kafka.indexer.broker.sasl.password: {{ .Values.global.kafka.indexer.broker.sasl.password | quote }}
  kafka.indexer.broker.rack.aware: {{ .Values.global.kafka.indexer.broker.rack.aware | quote }}
  #kafka.indexer.broker.rack.client: {{ .Values.global.kafka.indexer.broker.rack.client | quote }}  
  kafka.internal.broker.list: {{ .Values.global.kafka.internal.broker.list | quote }}
  kafka.topic.alert.response.out: {{ .Values.global.kafka.topic.alert.response.out | quote }}
  kafka.topic.tail.request.in: {{ .Values.global.kafka.topic.tail.request.in | quote }}
  kafka.topic.tail.response.out: {{ .Values.global.kafka.topic.tail.response.out | quote }}
  kafka.topic.index.live: {{ .Values.global.kafka.topic.index.live | quote }}
  kafka.topic.index.optimized: {{ .Values.global.kafka.topic.index.optimized | quote }}
  kafka.topic.index.labels:  {{ .Values.global.kafka.topic.index.labels | quote }}
  kafka.topic.optimize.request: {{ .Values.global.kafka.topic.optimize.request | quote }}
  kafka.topic.s3log.files: {{ .Values.global.kafka.topic.s3log.files | quote }}
  kafka.topic.cpanel.in: {{ .Values.global.kafka.topic.cpanel.in | quote }}
  kafka.topic.cpanel.out: {{ .Values.global.kafka.topic.cpanel.out | quote }}
  search.api.timeout.seconds: {{ .Values.global.livesearch.api.timeout.seconds | quote }}
  search.live.from.hours: {{ .Values.global.livesearch.live.from.hours | quote }}
  search.live.to.hours: {{ .Values.global.livesearch.live.to.hours | quote }}
  search.fixed.from.yyyymmddhh: {{.Values.global.fixedSearch.fixed.from.yyyymmddhh | quote }}
  search.fixed.to.yyyymmddhh: {{.Values.global.fixedSearch.fixed.to.yyyymmddhh | quote }}
  #gateway.api.http.port: {{ .Values.httpport | quote }}
  #gateway.search.timeout.seconds: {{ .Values.timeout | quote }}
  #gateway.search.url: {{ .Values.gatewayurl | quote }}
  ops.log.debug: {{ .Values.debug | quote }}
  search.api.grpc.port: {{ .Values.grpcport | quote }}
  search.api.response.max.mb: {{ .Values.maxmb | quote }}
  ops.license.url: {{ .Values.licenseurl | quote }} 
  spike.api.grpc.port: {{ .Values.spikeport | quote }}
  #ops.work.dir: {{ .Values.workdir | quote }}
  search.host: {{ .Values.searchhost | quote }}
  pulse.host: {{ .Values.pulsehost | quote }}
  pulse.port: {{ .Values.pulseport | quote }}
  #search.labels.exclude: "time"
  gateway.api.http.port: "9005"
  gateway.search.timeout.seconds: "120"
  gateway.search.url: "episilia-search:4040"
  ops.log.debug: "on"
  search.api.grpc.port: "4040"
  search.api.response.max.mb: "100"
  search.api.request.max.days: {{.Values.global.ondemandsearch.api.request.max.days | quote }}
  ops.license.url: "episilia-spike:50051"
  spike.api.grpc.port: "50051"
  ops.work.dir: "/data"
  search.host: "episilia-search:4040"
  spike.url: "http://episilia-spike:9090/"
  pulse.host: "dev-api-pulse.episilia.net"
  pulse.port: "50051"
  search.labels.exclude: "@timestamp,log"
  search.ops.index.cache.resetonstart: "true"
  search.ops.index.cache.disk.max.gb: "1"
  spike.grpc.server.port: "50051"
  spike.sql.source.paths: /sql.json
  spike.s3logs.publish.enable: "true"
  spike.s3logs.publish.seconds: {{ .Values.global.spike.s3logs.publish.seconds | quote }}
  spike.s3logs.publish.partitionwise: {{ .Values.global.spike.s3logs.publish.partitionwise | quote }}
  spike.login.mode: {{ .Values.global.spike.login.mode | quote }}
  spike.metadata.backfill.days: {{.Values.global.spike.metadata.backfill.days | quote }}
  spike.metadata.backfill.forceupdate: {{.Values.global.spike.metadata.backfill.forceupdate | quote }}
  spike.login.local.password.encryptionkey: {{ .Values.global.spike.login.local.password.encryptionkey | quote }}
  spike.login.google.clientid: {{ .Values.global.spike.login.google.clientid | quote }}
  spike.login.google.token: {{ .Values.global.spike.login.google.token | quote }}
  spike.login.okta.clientid: {{ .Values.global.spike.login.okta.clientid | quote }}
  spike.login.okta.token: {{ .Values.global.spike.login.okta.token | quote }}
  indexer.ops.s3.reader.enable: "true"
  cpanel.api.access.key: token
  cpanel.api.access.token: 98f4b6223f5908c16ed54962010500908d98f8c6
  cpanel.api.console.server: https://episilia-console-dev-pjyzk.ondigitalocean.app
  cpanel.gateway.server: episilia-gateway:9002 
