apiVersion: v1
kind: Service
metadata:
  name: {{ include "episilia-search-fixed.name" . }}
  labels:
    {{- include "episilia-search-fixed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4041
      protocol: TCP
      name: http
  selector:
    {{- include "episilia-search-fixed.selectorLabels" . | nindent 4 }}
