apiVersion: v1
kind: Pod
metadata:
  name: gateway-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "100"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
  - name: wait
    image: busybox
    command: ['sh', '-c', 'echo The gateway chart is being deployed last; sleep 10']
