apiVersion: v1
kind: Service
metadata:
  name: {{ include "episilia-gateway.name" . }}
  labels:
    {{- include "episilia-gateway.labels" . | nindent 4 }}
{{- with .Values.global.gateway.annotations }}
  annotations:
{{ toYaml . | indent 4  }}
{{- end }}
spec:
  type: {{ .Values.global.gateway.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9005
      protocol: TCP
      name: http
  selector:
    {{- include "episilia-gateway.selectorLabels" . | nindent 4 }}
