apiVersion: v1
kind: Service
metadata:
  name: {{ include "episilia-log-indexer.name" . }}
  labels:
    {{- include "episilia-log-indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "episilia-log-indexer.selectorLabels" . | nindent 4 }}
