apiVersion: v1
kind: Service
metadata:
  name: {{ include "episilia-logwatcher.name" . }}
  labels:
    {{- include "episilia-logwatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9070
      protocol: TCP
      name: http
  selector:
    {{- include "episilia-logwatcher.selectorLabels" . | nindent 4 }}
