name: Helm Deployment

on:
  push:
    branches:
      - main
      # - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version
      shell: bash

    - name: Helm Lint
      run: |
        helm lint charts/episilia-spike
      shell: bash

  deploy_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version
      shell: bash

    - name: Create Public Directory
      run: mkdir -p ./public
      shell: bash

    - name: List Files in Public Directory
      run: ls ./public
      shell: bash

    - name: Create Release Directory
      run: mkdir -p ./public/release
      shell: bash

    - name: Create robots.txt
      run: |
        echo "User-Agent: *" > ./public/robots.txt
        echo "Disallow: /" >> ./public/robots.txt
      shell: bash

    - name: Helm Dependency Update
      run: |
        helm dependency update charts/episilia-spike
      shell: bash

    - name: Helm Package
      run: |
        helm package charts/*
      shell: bash

    - name: Copy index.html to Release Directory
      run: cp -r index.html ./public/release
      shell: bash

    - name: Helm Repo Index
      run: |
        helm repo index --url https://91social.github.io/episilia-deploy/ .
      shell: bash

    - name: Move index.yaml and .tgz files
      run: |
      
        mv index.yaml ./public/release
        mv *.tgz ./public/release
      shell: bash

    - name: Print Working Directory
      run: pwd
      shell: bash

    - name: Print Deployment URL
      run: echo "https://91social.github.io/episilia-deploy/"
      shell: bash

    - name: List Files
      run: ls
      shell: bash

    - name: List Files in Public Directory
      run: ls ./public
      shell: bash

    - name: Cat index.yaml in Release Directory
      run: cat ./public/release/index.yaml
      shell: bash

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      if: github.ref == 'refs/heads/main'

  
