name: Helm Charts CI/CD

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [episilia-spike]  # Add other charts if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
        shell: bash

      - name: Helm Lint
        run: |
          helm lint charts/${{ matrix.chart }}
        shell: bash

  deploy_master:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        chart: [episilia-spike]  # Add other charts if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
        shell: bash

      - name: Create Public Directory
        run: mkdir -p ./public
        shell: bash

      - name: Create Release Directory
        run: mkdir -p ./public/release
        shell: bash

      - name: Create robots.txt
        run: |
          echo "User-Agent: *" > ./public/robots.txt
          echo "Disallow: /" >> ./public/robots.txt
        shell: bash

      - name: Helm Dependency Update
        run: |
          helm dependency update charts/${{ matrix.chart }}
        shell: bash

      - name: Helm Package
        run: |
          helm package charts/*
        shell: bash

      - name: Copy index.html to Release Directory
        run: cp -r index.html ./public/release
        shell: bash

      - name: Helm Repo Index
        run: |
          helm repo index --url https://91social.github.io/episilia-deploy/release .
        shell: bash

      - name: Move index.yaml and .tgz files
        run: |
          cp index.yaml ./public/release
          cp *.tgz ./public/release
        shell: bash

      - name: Print Working Directory
        run: pwd
        shell: bash

      - name: Print Deployment URL
        run: echo "https://91social.github.io/episilia-deploy/release"
        shell: bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
          charts_dir: ./public/release
          skip_existing: 
    if: github.ref == 'refs/heads/main'

          
  deploy_develop:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        chart: [episilia-spike]  # Add other charts if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
        shell: bash

      - name: Create Public Directory
        run: mkdir -p ./public
        shell: bash

      - name: Create Release Directory
        run: mkdir -p ./public/dev
        shell: bash

      - name: Create robots.txt
        run: |
          echo "User-Agent: *" > ./public/robots.txt
          echo "Disallow: /" >> ./public/robots.txt
        shell: bash

      - name: Helm Dependency Update
        run: |
          helm dependency update charts/${{ matrix.chart }}
        shell: bash

      - name: Helm Package
        run: |
          helm package charts/*
        shell: bash

      - name: Copy index.html to Release Directory
        run: cp -r index.html ./public/dev
        shell: bash

      - name: Helm Repo Index
        run: |
          helm repo index --url https://91social.github.io/episilia-deploy/dev .
        shell: bash

      - name: Move index.yaml and .tgz files
        run: |
          cp index.yaml ./public/dev
          cp *.tgz ./public/dev
        shell: bash

      - name: Print Working Directory
        run: pwd
        shell: bash

      - name: Print Deployment URL
        run: echo "https://91social.github.io/episilia-deploy/dev"
        shell: bash

      - name: Set up Chart Releaser
        run: |
          curl -LJO https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz
          tar -zxvf chart-releaser_1.6.0_linux_amd64.tar.gz
          mv cr /usr/local/bin/cr

      - name: Package and Release Helm Chart
        run: |
          cr upload -o owner -r repository -p ./public/dev --token ${{ secrets.CR_TOKEN }}
    if: github.ref == 'refs/heads/develop'
